### ISSUE TITLE
No logs or carriage return?

### ISSUE THREAD

**Issue by Bartlett-Will** [bartnv/portlurker#13]
After running cargo build, and executing sudo ./target/debug/portlurker (to execute with root privileges) control of the terminal is not returned. After testing, it doesn't record logs into the sqlite db connections table, or create a log file. Here is what I'm looking at: 
![image](https://user-images.githubusercontent.com/26557401/41253023-60876d54-6d95-11e8-80bb-e525e4e4b394.png)

**Comment by bartnv** [comment]
Well it's normal that portlurker remains in the foreground, even when logging to file or sqlite is enabled. When it is running, you should be able to (for instance) telnet to port 21 from another terminal and type some text to see it displayed within the portlurker window.

**Comment by mpentler** [comment]
Yep, i run it under screen for that very reason.

As for the no logs or SQLite database output that is strange.

Can you run the software and do as Bart suggests, maybe telnet in on another terminal and see if the software picks it up? Then I guess kill the app and show what - if anything - got outputted to the text log and SQL db
