### ISSUE TITLE
sql logging config bug

### ISSUE THREAD

**Issue by mpentler** [bartnv/portlurker#8]
Here: https://github.com/bartnv/portlurker/blob/6a629fdf0f5126ef8d570a0a68d5b61ca6338b20/src/main.rs#L144

We need to turn off logging after this line if the database file cannot be opened to stop problems later on.

The code will basically be a replica of this bit, but without making app mutable first as it already is at that point: https://github.com/bartnv/portlurker/blob/6a629fdf0f5126ef8d570a0a68d5b61ca6338b20/src/main.rs#L212-L214

**Comment by mpentler** [comment]
Alternative solution: only set sql_logging to true if the Connection:open works? That'd be a cleaner and shorter solution.

**Comment by bartnv** [comment]
Yeah, just move the app.sql_logging = true into the Ok() arm of the match on Connection::open() and put app.sql_logging = false in the Err() arm.

**Comment by mpentler** [comment]
Strictly speaking we don’t need the false as it’s already set when the variable is defined. Will do.

**Comment by mpentler** [comment]
Submitted a blind PR - I haven’t tested it but it looks ok. ;-)
